version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "10:00"
      timezone: "Europe/Zurich"
    open-pull-requests-limit: 3
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "10:00"
      timezone: "Europe/Zurich"
    open-pull-requests-limit: 3
